---
- name: install router
  become: yes
  hosts: all

  vars_prompt:
    # interfaces
    - name: internetif1
      prompt: Internet interface 1
      private: false

    - name: internetif2
      prompt: Internet interface 2
      private: false

    - name: localif
      prompt: Local interface
      private: false

    - name: wifiif
      prompt: Wifi interface
      private: false


    # ssids
    - name: ssid
      prompt: SSID
      private: false

    - name: passphrase
      prompt: Passphrase


  tasks:
  # apt
  - name: apt install
    apt:
      name: firmware-realtek, iptables-persistent, hostapd, squid-openssl, tcpdump, systemd-resolved
      update_cache: true


  # copying files
  - name: make iptables directory file
    file:
      path: /etc/iptables
      state: directory


  - name: make hostapd directory
    file:
      path: /etc/hostapd
      state: directory


  - name: copy networkd configs
    copy:
      src: ../files/router/networkd/
      dest: /etc/systemd/network/


  - name: copy iptables rules
    copy:
      src: ../files/router/rules.v4
      dest: /etc/iptables/rules.v4


  - name: copy resolved config
    copy:
      src: ../files/router/resolved.conf
      dest: /etc/systemd/resolved.conf


  - name: copy hostapd config
    copy:
      src: ../files/router/hostapd.conf
      dest: /etc/hostapd/hostapd.conf


  # networking
  - name: edit internet interface 1
    replace:
      path: /etc/systemd/network/internet-bonded.network
      regexp: 'CHANGEME_INTERNETIF1'
      replace: "{{ internetif1 }}"


  - name: edit internet interface 2
    replace:
      path: /etc/systemd/network/internet-bonded.network
      regexp: 'CHANGEME_INTERNETIF2'
      replace: "{{ internetif2 }}"


  - name: edit local interface
    replace:
      path: /etc/systemd/network/local.network
      regexp: 'CHANGEME_LOCALIF'
      replace: "{{ localif }}"


  - name: edit wifi interface wifi.network
    replace:
      path: /etc/systemd/network/wifi.network
      regexp: 'CHANGEME_WIFIIF'
      replace: "{{ wifiif }}"


  - name: stop and disable networking
    systemd:
      name: networking
      state: stopped
      enabled: false


  - name: start and enable networkd
    systemd:
      name: systemd-networkd
      state: started
      enabled: true


  - name: load iptables rules
    shell: iptables-restore /etc/iptables/rules.v4


  # resolved
  - name: stub resolv.conf
    file:
      path: /etc/resolv.conf
      src: /run/systemd/resolve/stub-resolv.conf
      state: link
      follow: false
      force: true


  - name: start and enable resolved
    systemd:
      name: systemd-resolved
      state: started
      enabled: true


  # hostapd
  - name: edit hostapd interface
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_WIFIIF'
      replace: "{{ wifiif }}"


  - name: edit hostapd SSID
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID'
      replace: "{{ ssid }}"


  - name: edit hostapd passphrase 1
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE'
      replace: "{{ passphrase }}"


  - name: start and enable hostapd
    systemd:
      name: hostapd
      state: started
      enabled: true
      masked: false


  - name: disable ipv6
    include: ../actions/disable_ipv6.yaml
