---
- name: install router
  become: yes
  hosts: all

  vars_prompt:
    - name: ssid1
      prompt: SSID 1
      private: false

    - name: passphrase1
      prompt: Passphrase 1


    - name: ssid2
      prompt: SSID 2
      private: false

    - name: passphrase2
      prompt: Passphrase 2


    - name: ssid3
      prompt: SSID 3
      private: false

    - name: passphrase3
      prompt: Passphrase 3


  tasks:
  # apt
  - name: configure backports
    lineinfile:
      path: /etc/apt/sources.list
      line: deb http://deb.debian.org/debian/ bullseye-backports


  - name: apt install
    apt:
      name: linux-image-amd64, firmware-realtek, iptables-persistent, hostapd
      update_cache: true


  - name: deconfigure backports
    lineinfile:
      path: /etc/apt/sources.list
      line: deb http://deb.debian.org/debian/ bullseye-backports
      state: absent


  # copying files
  - name: make iptables directory
    file:
      path: /etc/iptables
      state: directory


  - name: make hostapd directory
    file:
      path: /etc/hostapd
      state: directory


  - name: copy sysctl.conf
    copy:
      src: router/sysctl.conf
      dest: /etc/sysctl.conf


  - name: copy networkd configs
    copy:
      src: router/networkd/
      dest: /etc/systemd/network/


  - name: copy iptables rules
    copy:
      src: router/rules.v4
      dest: /etc/iptables/rules.v4


  - name: copy resolved config
    copy:
      src: router/resolved.conf
      dest: /etc/systemd/resolved.conf


  - name: copy hostapd config
    copy:
      src: router/hostapd.conf
      dest: /etc/hostapd/hostapd.conf


  - name: load sysctl config
    shell: sysctl -p


  # networking
  - name: stop and disable networking
    systemd:
      name: networking
      state: stopped
      enabled: false


  - name: start and enable networkd
    systemd:
      name: systemd-networkd
      state: started
      enabled: true


  - name: load iptables rules
    shell: iptables-restore /etc/iptables/rules.v4


  # resolved
  - name: stub resolv.conf
    file:
      path: /etc/resolv.conf
      src: /run/systemd/resolve/stub-resolv.conf
      state: link
      follow: false


  - name: start and enable resolved
    systemd:
      name: systemd-resolved
      state: started
      enabled: true


  # hostapd
  - name: edit hostapd SSID 1
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID_1'
      replace: "{{ ssid1 }}"


  - name: edit hostapd passphrase 1
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE_1'
      replace: "{{ passphrase1 }}"


  - name: edit hostapd SSID 2
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID_2'
      replace: "{{ ssid2 }}"


  - name: edit hostapd passphrase 2
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE_2'
      replace: "{{ passphrase2 }}"


  - name: edit hostapd SSID 3
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID_3'
      replace: "{{ ssid3 }}"


  - name: edit hostapd passphrase 3
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE_3'
      replace: "{{ passphrase3 }}"


  - name: start and enable hostapd
    systemd:
      name: hostapd
      state: started
      enabled: true
      masked: no
