---
- name: untar netboot.tar.gz
  unarchive:
    src: /tftp/netboot.tar.gz
    dest: /tftp/


- name: symlink grub
  file:
    src: /tftp/debian-installer/amd64/grub
    dest: /tftp/grub
    state: link


- name: symlink grubx64.efi
  file:
    src: /tftp/debian-installer/amd64/grubx64.efi
    dest: /tftp/grubx64.efi
    state: link
