---
- name: apt install
  apt:
    name: hostapd


- name: template hostapd config
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
  notify:
    - restart hostapd


- name: hostapd
  systemd:
    name: hostapd
    state: started
    enabled: true
