---
- name: apt install
  apt:
    name: dnsmasq


- name: include pxeboot tasks
  include_tasks: pxeboot.yaml
  when: "'pxeboot' in group_names"


- name: copy router dnsmasq config
  copy:
    src: router.conf
    dest: /etc/dnsmasq.conf
  notify:
    - restart dnsmasq


- name: dnsmasq service
  systemd:
    name: dnsmasq
    state: started
    enabled: true
