---
- name: gitlab
  become: yes
  hosts: all


  vars_prompt:
  - name: external_url
    prompt: External URL
    private: false


  tasks:
  - name: apt install
    apt:
      name: curl, openssh-server, ca-certificates, perl, postfix
      update_cache: true


  - name: download gitlab repo script
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
      checksum: sha256:b04953928c105f5283816c633c1ff721ed81ced10eb3e3223677c250fb4af987
      dest: /tmp/script.deb.sh
      mode: 'u=rwx,g=r,o=r'


  - name: run gitlab repo script
    script: /tmp/script.deb.sh


  - name: apt install gitlab
    apt:
      name: gitlab-ce
      update_cache: true

    environment:
      EXTERNAL_URL: "{{ external_url }}"


  - name: check if initial_root_password exists
    stat:
      path: /etc/gitlab/initial_root_password
    register: initial_root_password_exists


  - name: register initial root password
    shell: 'cat /etc/gitlab/initial_root_password'
    register: initial_root_password
    when: initial_root_password_exists.stat.exists


  - name: display initial root password
    debug:
      msg: "Initial root password: {{ initial_root_password }}"
    when: initial_root_password_exists.stat.exists


# todo:
#   https://docs.gitlab.com/ee/install/next_steps.html
#   for now, just having gitlab with a fqdn will be a big step in the right direction
