---
- name: pipxeboot
  become: yes
  hosts: all


  vars_prompt:
  - name: wiredif
    prompt: Wired Interface
    private: false


  tasks:
  - import_tasks: ../actions/apt_full_upgrade.yaml
  - import_tasks: ../actions/kill_pi_services.yaml


  - name: apt install
    apt:
      name: dnsmasq


  - name: copy networkd config
    copy:
      src: ../files/pipxeboot/networkd/
      dest: /etc/systemd/network/


  - name: replace eth0
    replace:
      path: /etc/systemd/network/eth0.network
      regexp: eth0
      replace: "{{ wiredif }}"


  - name: copy dnsmasq config
    copy:
      src: ../files/pipxeboot/dnsmasq.conf
      dest: /etc/dnsmasq.conf


  - name: make tftp directory
    file:
      path: /tftp
      state: directory


  - name: download netboot.tar.gz
    get_url:
      url: https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/netboot.tar.gz
      checksum: sha256:https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/SHA256SUMS
      dest: /tftp/netboot.tar.gz


  - name: untar netboot.tar.gz
    unarchive:
      src: /tftp/netboot.tar.gz
      dest: /tftp/


  - name: symlink grub
    file:
      src: /tftp/debian-installer/amd64/grub
      dest: /tftp/grub
      state: link


  - name: symlink grub.efi
    file:
      src: /tftp/debian-installer/amd64/grubx64.efi
      dest: /tftp/grubx64.efi
      state: link


  - name: start and enable dnsmasq
    systemd:
      name: dnsmasq
      state: running
      enabled: true
