---
- name: install router
  become: yes
  hosts: all

  vars_prompt:
    # interfaces
    - name: internetif1
      prompt: Internet interface 1
      private: false

    - name: internetif2
      prompt: Internet interface 2
      private: false

    - name: localif
      prompt: Local interface
      private: false

    - name: wifiif
      prompt: Wifi interface
      private: false


    # ssids
    - name: ssid1
      prompt: SSID 1
      private: false

    - name: passphrase1
      prompt: Passphrase 1

    - name: ssid2
      prompt: SSID 2
      private: false

    - name: passphrase2
      prompt: Passphrase 2

    - name: ssid3
      prompt: SSID 3
      private: false

    - name: passphrase3
      prompt: Passphrase 3


  tasks:
  # apt
  - name: apt install
    apt:
      name: firmware-realtek, iptables-persistent, hostapd, squid-openssl, tcpdump, systemd-resolved
      update_cache: true


  # copying files
  - name: make iptables directory file
    file:
      path: /etc/iptables
      state: directory


  - name: make hostapd directory
    file:
      path: /etc/hostapd
      state: directory


  - name: make squid directory
    file:
      path: /etc/squid
      state: directory


  - name: make squid cert directory
    file:
      path: /etc/squid/certs
      state: directory


  - name: copy sysctl.conf
    copy:
      src: ../files/router/sysctl.conf
      dest: /etc/sysctl.conf


  - name: copy networkd configs
    copy:
      src: ../files/router/networkd/
      dest: /etc/systemd/network/


  - name: copy iptables rules
    copy:
      src: ../files/router/rules.v4
      dest: /etc/iptables/rules.v4


  - name: copy resolved config
    copy:
      src: ../files/router/resolved.conf
      dest: /etc/systemd/resolved.conf


  - name: copy hostapd config
    copy:
      src: ../files/router/hostapd.conf
      dest: /etc/hostapd/hostapd.conf


  - name: copy squid config
    copy:
      src: ../files/router/squid.conf
      dest: /etc/squid/squid.conf


  - name: copy tcpdump unit file
    copy:
      src: ../files/router/tcpdump.service
      dest: /etc/systemd/system/tcpdump.service


  - name: load sysctl config
    shell: sysctl -p


  # networking
  - name: edit internet interface 1
    replace:
      path: /etc/systemd/network/internet-bonded.network
      regexp: 'CHANGEME_INTERNETIF1'
      replace: "{{ internetif1 }}"


  - name: edit internet interface 2
    replace:
      path: /etc/systemd/network/internet-bonded.network
      regexp: 'CHANGEME_INTERNETIF2'
      replace: "{{ internetif2 }}"


  - name: edit local interface
    replace:
      path: /etc/systemd/network/local-bridged.network
      regexp: 'CHANGEME_LOCALIF'
      replace: "{{ localif }}"


  - name: edit wifi interface
    replace:
      path: /etc/systemd/network/local-bridged.network
      regexp: 'CHANGEME_WIFIIF'
      replace: "{{ wifiif }}"


  - name: stop and disable networking
    systemd:
      name: networking
      state: stopped
      enabled: false


  - name: start and enable networkd
    systemd:
      name: systemd-networkd
      state: started
      enabled: true


  - name: load iptables rules
    shell: iptables-restore /etc/iptables/rules.v4


  # resolved
  - name: stub resolv.conf
    file:
      path: /etc/resolv.conf
      src: /run/systemd/resolve/stub-resolv.conf
      state: link
      follow: false
      force: true


  - name: start and enable resolved
    systemd:
      name: systemd-resolved
      state: started
      enabled: true


  # hostapd
  - name: edit hostapd SSID 1
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID_1'
      replace: "{{ ssid1 }}"


  - name: edit hostapd passphrase 1
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE_1'
      replace: "{{ passphrase1 }}"


  - name: edit hostapd SSID 2
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID_2'
      replace: "{{ ssid2 }}"


  - name: edit hostapd passphrase 2
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE_2'
      replace: "{{ passphrase2 }}"


  - name: edit hostapd SSID 3
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_SSID_3'
      replace: "{{ ssid3 }}"


  - name: edit hostapd passphrase 3
    replace:
      path: /etc/hostapd/hostapd.conf
      regexp: 'CHANGEME_PASSPHRASE_3'
      replace: "{{ passphrase3 }}"


  - name: start and enable hostapd
    systemd:
      name: hostapd
      state: started
      enabled: true
      masked: false


  # squid
  - name: check if cert exists
    stat:
      path: /etc/squid/certs/cert.pem
    register: cert


  - name: check if key exists
    stat:
      path: /etc/squid/certs/key.pem
    register: key


  - name: squid generate certs
    shell: openssl req -x509 -newkey rsa:2048 -keyout /etc/squid/certs/key.pem -out /etc/squid/certs/cert.pem -sha256 -days 365
    when: cert.stat.exists == false or key.stat.exists == false


  - name: start and enable squid
    systemd:
      name: squid
      state: started
      enabled: true


  # tcpdump
  - name: start and enable tcpdump
    systemd:
      name: tcpdump
      state: started
      enabled: true
