---
- name: copy pxeboot networkd config
  copy:
    src: ../files/pxeboot/networkd/eth0.network
    dest: /etc/systemd/network/
  when: "'pxeboot' in group_names"
  notify:
    - restart networkd


- name: networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: true
