---
- name: install openssh-server
  apt:
    name: openssh-server


- name: copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd


- name: ssh
  systemd:
    name: sshd
    state: started
    enabled: true
