---
- name: install openssh-server
  apt:
    name: openssh-server


- name: copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd
  when: "'router' not in group_names"


- name: sshd
  systemd:
    name: ssh
    state: started
    enabled: true
